apiVersion: apps/v1
kind: Deployment
metadata:
  name: andybot
  namespace: discord-bots
  labels:
    app: andybot
    language: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andybot
  template:
    metadata:
      labels:
        app: andybot
        language: go
    spec:
      containers:
        - name: andybot
          image: 192.168.1.245:5000/andybot:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: auth
              mountPath: /app/auth.txt
              subPath: auth.txt
              readOnly: true
      volumes:
        - name: auth
          secret:
            secretName: andybot-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: andybot
  namespace: discord-bots
spec:
  selector:
    app: andybot
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
