apiVersion: apps/v1
kind: Deployment
metadata:
  name: jailbot
  namespace: discord-bots
  labels:
    app: jailbot
    language: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jailbot
  template:
    metadata:
      labels:
        app: jailbot
        language: nodejs
    spec:
      containers:
      - name: jailbot
        image: localhost:5000/jailbot:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        volumeMounts:
        - name: auth
          mountPath: /app/auth.json
          subPath: auth.json
          readOnly: true
      volumes:
      - name: auth
        secret:
          secretName: jailbot-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jailbot
  namespace: discord-bots
spec:
  selector:
    app: jailbot
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
