apiVersion: apps/v1
kind: Deployment
metadata:
  name: owobot
  namespace: discord-bots
  labels:
    app: owobot
    language: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owobot
  template:
    metadata:
      labels:
        app: owobot
        language: nodejs
    spec:
      containers:
      - name: owobot
        image: localhost:5000/owobot:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        volumeMounts:
        - name: auth
          mountPath: /app/auth.json
          subPath: auth.json
          readOnly: true
      volumes:
      - name: auth
        secret:
          secretName: owobot-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: owobot
  namespace: discord-bots
spec:
  selector:
    app: owobot
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
