apiVersion: apps/v1
kind: Deployment
metadata:
  name: scribebot
  namespace: discord-bots
  labels:
    app: scribebot
    language: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scribebot
  template:
    metadata:
      labels:
        app: scribebot
        language: python
    spec:
      containers:
      - name: scribebot
        image: localhost:5000/scribebot:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        volumeMounts:
        - name: auth
          mountPath: /app/auth.txt
          subPath: auth.txt
          readOnly: true
      volumes:
      - name: auth
        secret:
          secretName: scribebot-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: scribebot
  namespace: discord-bots
spec:
  selector:
    app: scribebot
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
