apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsb
  namespace: discord-bots
  labels:
    app: wsb
    language: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsb
  template:
    metadata:
      labels:
        app: wsb
        language: go
    spec:
      containers:
      - name: wsb
        image: localhost:5000/wsb:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: auth
          mountPath: /app/auth.txt
          subPath: auth.txt
          readOnly: true
      volumes:
      - name: auth
        secret:
          secretName: wsb-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wsb
  namespace: discord-bots
spec:
  selector:
    app: wsb
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
